# CMake generated Testfile for 
# Source directory: /home/shiyanlou/Code/make/cmake-3.7.0-rc1/Tests/CMakeTests
# Build directory: /home/shiyanlou/Code/make/cmake-3.7.0-rc1/Tests/CMakeTests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(CMake.List "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/bin/cmake" "-P" "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/Tests/CMakeTests/ListTest.cmake")
add_test(CMake.VariableWatch "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/bin/cmake" "-P" "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/Tests/CMakeTests/VariableWatchTest.cmake")
add_test(CMake.Include "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/bin/cmake" "-P" "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/Tests/CMakeTests/IncludeTest.cmake")
add_test(CMake.FindBase "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/bin/cmake" "-P" "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/Tests/CMakeTests/FindBaseTest.cmake")
add_test(CMake.Toolchain "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/bin/cmake" "-P" "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/Tests/CMakeTests/ToolchainTest.cmake")
add_test(CMake.GetFilenameComponentRealpath "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/bin/cmake" "-P" "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/Tests/CMakeTests/GetFilenameComponentRealpathTest.cmake")
add_test(CMake.Version "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/bin/cmake" "-P" "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/Tests/CMakeTests/VersionTest.cmake")
add_test(CMake.Message "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/bin/cmake" "-P" "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/Tests/CMakeTests/MessageTest.cmake")
add_test(CMake.File "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/bin/cmake" "-P" "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/Tests/CMakeTests/FileTest.cmake")
add_test(CMake.SeparateArguments "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/bin/cmake" "-P" "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/Tests/CMakeTests/SeparateArgumentsTest.cmake")
add_test(CMake.ImplicitLinkInfo "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/bin/cmake" "-P" "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/Tests/CMakeTests/ImplicitLinkInfoTest.cmake")
add_test(CMake.ModuleNotices "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/bin/cmake" "-P" "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/Tests/CMakeTests/ModuleNoticesTest.cmake")
add_test(CMake.GetProperty "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/bin/cmake" "-P" "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/Tests/CMakeTests/GetPropertyTest.cmake")
add_test(CMake.If "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/bin/cmake" "-P" "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/Tests/CMakeTests/IfTest.cmake")
add_test(CMake.String "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/bin/cmake" "-P" "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/Tests/CMakeTests/StringTest.cmake")
add_test(CMake.Math "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/bin/cmake" "-P" "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/Tests/CMakeTests/MathTest.cmake")
add_test(CMake.CMakeMinimumRequired "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/bin/cmake" "-P" "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/Tests/CMakeTests/CMakeMinimumRequiredTest.cmake")
add_test(CMake.CompilerIdVendor "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/bin/cmake" "-P" "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/Tests/CMakeTests/CompilerIdVendorTest.cmake")
add_test(CMake.ProcessorCount "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/bin/cmake" "-DKWSYS_TEST_EXE=/home/shiyanlou/Code/make/cmake-3.7.0-rc1/Source/kwsys/cmsysTestsCxx" "-P" "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/Tests/CMakeTests/ProcessorCountTest.cmake")
add_test(CMake.PushCheckState "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/bin/cmake" "-P" "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/Tests/CMakeTests/PushCheckStateTest.cmake")
add_test(CMake.While "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/bin/cmake" "-P" "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/Tests/CMakeTests/WhileTest.cmake")
add_test(CMake.CMakeHostSystemInformation "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/bin/cmake" "-P" "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/Tests/CMakeTests/CMakeHostSystemInformationTest.cmake")
add_test(CMake.FileDownload "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/bin/cmake" "-P" "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/Tests/CMakeTests/FileDownloadTest.cmake")
set_tests_properties(CMake.FileDownload PROPERTIES  PASS_REGULAR_EXPRESSION "file already exists with expected MD5 sum")
add_test(CMake.FileDownloadBadHash "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/bin/cmake" "-P" "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/Tests/CMakeTests/FileDownloadBadHashTest.cmake")
set_tests_properties(CMake.FileDownloadBadHash PROPERTIES  WILL_FAIL "TRUE")
add_test(CMake.FileUpload "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/bin/cmake" "-P" "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/Tests/CMakeTests/FileUploadTest.cmake")
add_test(CMake.ELF "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/bin/cmake" "-P" "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/Tests/CMakeTests/ELFTest.cmake")
add_test(CMake.EndStuff "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/bin/cmake" "-Ddir:STRING=/home/shiyanlou/Code/make/cmake-3.7.0-rc1/Tests/CMakeTests/EndStuffTest" "-P" "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/Tests/CMakeTests/EndStuffTest.cmake")
add_test(CMake.GetPrerequisites "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/bin/cmake" "-DCTEST_CONFIGURATION_TYPE:STRING=\${CTEST_CONFIGURATION_TYPE}" "-P" "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/Tests/CMakeTests/GetPrerequisitesTest.cmake")
add_test(CMake.PolicyCheck "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/bin/cmake" "-DCMake_BINARY_DIR:PATH=/home/shiyanlou/Code/make/cmake-3.7.0-rc1" "-DCMake_SOURCE_DIR:PATH=/home/shiyanlou/Code/make/cmake-3.7.0-rc1" "-DGIT_EXECUTABLE:STRING=/usr/bin/git" "-P" "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/Tests/CMakeTests/PolicyCheckTest.cmake")
add_test(CMake.CheckSourceTree "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/bin/cmake" "-DCMake_BINARY_DIR:PATH=/home/shiyanlou/Code/make/cmake-3.7.0-rc1" "-DCMake_SOURCE_DIR:PATH=/home/shiyanlou/Code/make/cmake-3.7.0-rc1" "-DGIT_EXECUTABLE:STRING=/usr/bin/git" "-DHOME:STRING=/root" "-P" "/home/shiyanlou/Code/make/cmake-3.7.0-rc1/Tests/CMakeTests/CheckSourceTreeTest.cmake")
